### ISSUE TITLE
[Bug] In V7, react-static-plugin-sass plugin builds with noisy warnings: "Replace Autoprefixer browsers option to Browserslist config...."

### ISSUE THREAD

**Issue by erchaves** [react-static/react-static#1239] opened 2019-06-25 00:18 UTC
### Bug:

Since upgrading react-static to V7, the react-static-plugin-sass plugin leaves very noisy warnings when it builds.

The warnings repeat multiple times (one time per each scss import maybe?). It reads:

> 
>   Replace Autoprefixer browsers option to Browserslist config.
>   Use browserslist key in package.json or .browserslistrc file.
> 
>   Using browsers option cause some error. Browserslist config 
>   can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> 
>   If you really need to use option, rename it to overrideBrowserslist.
> 
>   Learn more at:
>   https://github.com/browserslist/browserslist#readme
>   https://twitter.com/browserslist
> 

![Screen Shot 2019-06-24 at 7 54 14 PM](https://user-images.githubusercontent.com/302309/60059609-2e384080-96bb-11e9-9f1a-91a45fea0902.png)

The warning refers to a [browserslist readme](https://github.com/browserslist/browserslist#readme) which suggests to add the following to the package.json:
```
  "browserslist": [
    "defaults"
  ]
```
But this does not seem to help.  Perhaps, the autoprefix settings need to adjusted in a [webpack settings file like this](https://github.com/nozzle/react-static/blob/a910a1f6f3fb9013cf4f311b721b2fac93f72709/packages/react-static/src/static/webpack/rules/cssLoader.js)?

### Environment

Using react-static: 7.0.0 and 
Using react-static-plugin-sass: 7.1.0
[Bug] In V7, react-static-plugin-sass plugin builds with noisy warnings: "Replace Autoprefixer browsers option to Browserslist config...."

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 491.36 MB / 16.00 GB
    Shell: 5.4.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Chrome Canary: 77.0.3832.0
    Firefox: 65.0.1
    Safari: 12.1.1
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-static: ^7.0.0 => 7.1.0 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sass: ^7.1.0 => 7.1.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0 

### Steps to Reproduce the problem
1. Use a freshly installed react-static template. 
2. Install react-static-plugin-sass
3. Add "react-static-plugin-sass" to the plugins section of the static.config.js file.
3. Run `yarn start` or `yarn build`.
4. The app does work, but the console is filled with noisy warnings.

### Reproducible Demo
You can refer to this test repo here:
https://github.com/erchaves/react-static-template

### Thanks
Thanks for the great project!

-Eric 
[Syllablehq.com](https://www.syllablehq.com/)

**Comment by Wavez** [comment] 2019-06-25 10:44
duplicate of https://github.com/nozzle/react-static/issues/1220

**Comment by erchaves** [comment] 2019-06-25 13:33
Ahh, I see that duplicate now. Thanks @Wavez, I missed that before.

**Comment by SleeplessByte** [comment] 2019-08-14 16:38
Fixed via https://github.com/react-static/react-static/pull/1283/commits/7c244e45dbdbf8dd12cc4c09ad412253db869cf2

**Closed by SleeplessByte** 2019-08-14 16:38 UTC
Labels: duplicate :repeat:
