### ISSUE TITLE
[Bug] Navbar and Footer Rendered before page rendered, causing the footer to move down (CLS issue).

### ISSUE THREAD

**Issue by user9747** [react-static/react-static#1594] opened 2021-04-01 04:31 UTC
My App.js

```js
 <Root>
      <React.Suspense fallback={<Loader />}>
          <Navbar />     
          <Routes path='*' />
          <Footer />
      </React.Suspense>
    </Root>
```

**Comment by SleeplessByte** [comment] 2021-04-01 10:14
I don't know how you expect people to help you if this is all the effort you put in opening an issue. 

This is not a bug, so I will close this.

**Closed by SleeplessByte** 2021-04-01 10:14 UTC
Labels: bug :bug:
