### ISSUE TITLE
getRoutes dev Argument is Undefined

### ISSUE THREAD

**Issue by kalinchuk** [react-static/react-static#1209] opened 2019-05-29 20:46 UTC
Reference:

```
getRoutes: async ({ dev }) => {
  console.log(dev);
}
```

When getRoutes is called during a build, the `dev` argument is always `undefined`.

### Environment

```
npx: installed 1 in 1.412s

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 864.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-dom: ^16.8.6 => 16.8.6 
    react-hot-loader: ^4.8.8 => 4.8.8 
    react-static: ^7.0.10 => 7.0.10 
    react-static-plugin-reach-router: ^7.0.10 => 7.0.10 
    react-static-plugin-sass: ^7.0.10 => 7.0.10 
    react-static-plugin-sitemap: ^7.0.10 => 7.0.10 
  npmGlobalPackages:
    react-static: 6.3.3
```

### Expected Behavior

`dev` should be a `true` or `false`.

**Comment by JoshClose** [comment] 2019-12-31 17:11
This is the same with `getSiteData` too. I see that there is a property `stage` that is set to `dev` when running locally. Can we reliably use `dev = stage === "dev"` in place of the missing `dev` property?

**Comment by SleeplessByte** [comment] 2020-01-02 05:49
I actually don't know the answer to this. When that code was written, we were not around yet. In the new RS 8, these variables no longer exist. The issue is that the values passed to this function are not "created" in a single entry point, but are an accumulation of function calls.

If you're trying to figure out if you are in "yarn start" instead of "yarn build" etc, you're probably better off checking the REACT_STATIC_ENV variable or passing your own variable, as that will always be consistent :)

**Comment by JoshClose** [comment] 2020-01-02 18:56
The config examples in the docs still show a `dev` property.

https://github.com/react-static/react-static/blob/master/docs/config.md#getroutes

**Comment by SleeplessByte** [comment] 2020-01-08 04:19
Yes, those docs are not perfectly up to date. There are multiple issues regarding that, but it's on track of being fixed in the next major :)

**Closed** 2022-04-29 14:55 UTC
Labels: wontfix :no_good_woman:
