### ISSUE TITLE
[Bug] `build` leaks absolute path to site directory

### ISSUE THREAD

**Issue by abiro** [react-static/react-static#1355] opened 2020-01-06 16:29 UTC
### Reporting a bug?

Running `build` results in paths that leak the absolute path (including user's home directory) to site directory.

### Environment

```

  System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Firefox: 71.0
  npmPackages:
    react: ^16.9.0 => 16.12.0 
    react-dom: ^16.9.0 => 16.12.0 
    react-static: ^7.2.0 => 7.2.3 
    react-static-plugin-reach-router: ^7.2.0 => 7.2.3 
    react-static-plugin-sitemap: ^7.2.0 => 7.2.3 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3 
  npmGlobalPackages:
    react-static: 7.2.3

```

### Steps to Reproduce the problem

1.  Install `react-static` version `7.2.3` with `yarn global add react-static`
2.  `react-static create`
3.  Select "basic" presets.
4. `cd my-static-site`
5. `yarn build`
6. `find dist -type f | grep home`

Result:

```
dist/templates/home/abiro/repos/my-static-site/src/pages/index.af23ae39.js
dist/templates/home/abiro/repos/my-static-site/src/pages/blog.c17f1160.js
dist/templates/home/abiro/repos/my-static-site/src/pages/404.535705df.js
dist/templates/home/abiro/repos/my-static-site/src/pages/about.0cba9bef.js
dist/templates/home/abiro/repos/my-static-site/src/containers/Post.110c8ebb.js
```

### Expected Behavior

Page and container templates shouldn't leak path to the `my-static-site` directory on the user's computer.

**Comment by abiro** [comment] 2020-01-06 17:19
Downgrading to `react-static@7.1.0` fixes the issue.

**Comment by SleeplessByte** [comment] 2020-01-07 06:51
Duplicate of https://github.com/react-static/react-static/issues/1303

**Closed by SleeplessByte** 2020-01-07 06:51 UTC
Labels: bug :bug:
