### ISSUE TITLE
Hot reloading seems broken on V6

### ISSUE THREAD

**Issue by Pixelatex** [react-static/react-static#894] opened 2018-12-18 11:29 UTC
After fixing #876, I noticed that the hot reloading is having issues in all examples, even the basic one.

The hot reloading module recommends using hot(app) instead of hot(module)(app). But while this does work, it seems to reload the route component only and removes the app html (<nav> for example).

We may need to downgrade the hot reloading to an older version or update our usage to make it work with new version.

**Comment by leekad** [comment] 2018-12-18 11:30
Checked, HMR only reload the index.js and App.js. All others not working

**Comment by Pixelatex** [comment] 2018-12-18 11:32
Not sure if I can look into it today so made the ticket here so someone else may fix it sooner 😄

**Comment by Herohtar** [comment] 2018-12-18 16:39
This is the same issue that v5 had that was supposedly fixed in v6; did it work at some point?

**Comment by tannerlinsley** [comment] 2018-12-18 16:56
It's been a constant battle. React hot loader is in disarray right now and
especially is having a hard time with the 16.6 and 16.7 versions of react.
Unfortunately this is an upstream issue for the most part and we'll have to
wait and see what happens but we're going to do everything we can to get it
to work in its current state.

**Comment by leekad** [comment] 2018-12-18 17:09
Disable code splitting on dev should work, doesnt it?

**Comment by tannerlinsley** [comment] 2018-12-18 17:20
Code Splitting doesn't happen in dev in v6 at all. If you look at `tmp/dev-server/react-static-templates.js` you'll see it's just raw imports :)

**Comment by sgup** [comment] 2018-12-18 22:31
I'm having an issue where I have to re-start the whole server after a few minutes. I'm already refreshing the browser in between edits to see the updates, but after some minutes even the refresh stops working and waiting perpetually for the site to load. Is this related?

Running fresh install with styled-components and Pixelatex's recent edits.

**Comment by tannerlinsley** [comment] 2018-12-18 22:34
It could be related yes. The hot-reloading like you can see above right now is very finicky. It's honestly never worked quite right since React 16.6 and I have a really good feeling that it's upstream in RHL.

Ultimately, @theKashey would know more about this issue, since he's heading up RHL nowadays. I know he is also working closely with Gatsby to solve this problem on their end, too. It's likely the solution for them will work for us too (probably not as complex to implement though, since the hot-reloading for React-Static lives in user-land, instead of in React-Static)

**Comment by theKashey** [comment] 2018-12-19 04:38
1. React-Hot-Loader 4.3.0 and below was not supporting `forwardProps`, thus StyleComponents were broken.
2. React-Hot-Loader 4.6.1 and below has a bug if you call `hot(module)(app)` twice per one module. Resolved in 4.6.2 yesterday - https://github.com/gatsbyjs/gatsby/issues/10528
3. There is a bug with HOC of different sort (for example Redux), where any your component could replace any your component. Found it just yesterday.

**Comment by theKashey** [comment] 2018-12-19 04:40
Just give me some example to reproduce, and I'll fix it.

**Comment by tannerlinsley** [comment] 2018-12-19 06:05
Start with installing react static and running `react-static create` and
choosing the basic template. From there you can experiment with different
RHL configurations and also try editing any of the src files. It's very
straight forward, almost like CRA.

**Comment by Pixelatex** [comment] 2018-12-19 08:15
@theKashey the weird thing is that it hot reloads the pages... but... it ditches all the html in app.js.

pre-hot-reloaded app.js does this:

```
 <nav>
      <Link to="/">Home</Link>
      <Link to="/about">About</Link>
      <Link to="/blog">Blog</Link>
    </nav>
    <div className="content">
      <Routes />
    </div>
```
After hotreload, this is what you get:

```
<Routes />
```

**Comment by theKashey** [comment] 2018-12-19 09:41
@tannerlinsley - react-hot-loader/babel is applied twice :)

**Comment by theKashey** [comment] 2018-12-19 10:06
Some packages are inside node_modules, some packages are inside react-static. It always uses the "closest one", as result - just not work.

react/react-dom/react-hot-loader should be singlentones.
<img width="303" alt="screen shot 2018-12-19 at 9 04 45 pm" src="https://user-images.githubusercontent.com/582410/50213489-e5cd5c80-03d1-11e9-90ca-2261ceca5d53.png">

**Comment by tannerlinsley** [comment] 2018-12-19 18:03
Interesting. I'll try and correct this and see if it changes anything.

**Comment by ScriptedAlchemy** [comment] 2018-12-21 08:07
@theKashey thanks for stepping in here! Really appreciate it when the authors themselves come forwards to help. It’s few and far between. #broforce

**Comment by kirklikecaptain** [comment] 2018-12-25 06:02
I've been noticing this behavior too. 
react-static v 6.0.18


For me, it's only an issue in page-level components. HMR seems to work fine for an App level component and components nested within page-level components, just not the page level components themselves. 

Making changes to the page components seems to trigger a rebuild/update which is logged by node, it's just that the browser doesn't update until the page is refreshed. 

Perhaps the issue has something to do with how the Routes component works. Not sure, but I thought this info might be helpful.

**Comment by ScriptedAlchemy** [comment] 2018-12-26 08:34
Could be my code-splitting points? I’ll check my HMR and also run it past the author of react hot loader himself.

**Comment by theKashey** [comment] 2018-12-26 21:02
@ScriptedAlchemy - check for duplications
- react packages duplication I've noticed in my example
- babel plugins applied twice

Something is very wrong here, and one have to fix it prior any other changes.

**Comment by ScriptedAlchemy** [comment] 2018-12-30 00:53
Thanks Anton, looks like we need to do some digging

**Comment by sw-yx** [comment] 2019-01-29 21:38
not stale

**Comment by tannerlinsley** [comment] 2019-01-31 16:57
Been a bit since I've dug into this. Any more info from anyone on this one? Still experiencing this?

**Comment by ozburo** [comment] 2019-01-31 18:57
Yeah this is still happening... I can get hot-reloading working on a fresh project install, but as soon as I need to rebuild my `node_modules` it's lost.

For example, I had to rebuild the node modules w/ `npm install` after trying to add "styled-components" and it removing a bunch of packages that we're needed, namely "axios".

Ofc I don't know _why_ it does this, but what can you do...

For illustrative purposes, if you create a blank/new react-create project:

$ yarn add react-static-plugin-styled-components

$ npm install --save styled-components

$ yarn start

It blows up w/ "can't find axios" b/c styled-components removed it (along w/ 105 other packages).

*shrugs*

**Comment by theKashey** [comment] 2019-01-31 20:50
stop stop stop stop stop.
You __cant't__ do `yarn add react-static-plugin-styled-components` and then `npm install`. They are killing each other as long one uses `yarn.lock` and another `package.lock`.

There can be only one!

**Comment by ozburo** [comment] 2019-01-31 21:38
@theKashey On snap! Ok lesson learned 👍

**Comment by cy** [comment] 2019-02-01 21:21
also seeing this issue, used react-static create basic app, with:
```
    "react-hot-loader": "^4.3.12",
    "react-static": "^6.0.18",
    "react-static-plugin-styled-components": "6.3.0",
```
browser says `React-Static data hot-loader websocket connected. Listening for data changes...`, console updates with `Rebuilding...Build complete`, but browser does not update.

**Comment by theKashey** [comment] 2019-03-04 01:01
Hey, stalebot! Issues would not fix themselves!

**Comment by tannerlinsley** [comment] 2019-03-07 18:03
I know this is still going on, but would just like to check in and say that we're still looking into this. It's top priority.

**Comment by kirklikecaptain** [comment] 2019-03-10 23:48
My build has been working as expected. I'm using React Static 6.3.6 and I bumped React Hot Loader to `"react-hot-loader": "4.6.3"`. That seemed to do the trick. Here's the repo - [https://github.com/kirklikecaptain/afov-react](https://github.com/kirklikecaptain/afov-react) -- File save to browser update takes < 1s. 

Here's my root level file that handles the RHL logic:

```
import React from 'react';
import ReactDOM from 'react-dom';

// Your top level component
import App from './app/App';
import ReactGA from 'react-ga';

// Export your top level component as JSX (for static rendering)
export default App;

// Render your app
if (typeof document !== 'undefined') {

	ReactGA.initialize('UA-117674715-1');


  const renderMethod = module.hot ? ReactDOM.render : ReactDOM.hydrate || ReactDOM.render;

  const render = Comp => {
    renderMethod(<Comp />, document.getElementById('root'));
  };

  // Render!
  render(App);

  // Hot Module Replacement
  if (module.hot) {
    module.hot.accept('./app/App', () => render(require('./app/App').default));
  }
}
```

**Comment by theKashey** [comment] 2019-03-11 02:33
You shall not use `module.hot.accept` if you have `React-Hot-Loader`. It is disabled out of HMR event, it might not detect here.

**Comment by cassianomon** [comment] 2019-03-17 02:00
Just installed and it still happening.

**Comment by theKashey** [comment] 2019-03-17 04:30
@cassianomon - what is happening?

**Comment by cassianomon** [comment] 2019-03-17 19:46
@theKashey I did a fresh install, choose basic template and it doesnt reload when I change .js files, only reloads if I change the main index.js.

**Comment by tannerlinsley** [comment] 2019-04-01 17:26
Hot reloading should now work flawlessly in v7 🤞. If it does not, please reopen a *NEW* issue. Thanks!

**Closed as completed by tannerlinsley** 2019-04-01 17:26 UTC
Labels: bug :bug:
